### ISSUE TITLE
Make extension method public

### ISSUE THREAD

**Issue by matt-psaltis** [VerifyTests/Verify.ImageMagick#391]
Could we get this extension method made public to support adding additional conversions that ImageMagic already supports?

https://github.com/VerifyTests/Verify.ImageMagick/blob/d2b9508075710b2a327d9e9951acc4ac6883b6cb/src/Verify.ImageMagick/VerifyImageMagick_Pdf.cs#L11

**Comment by SimonCropp** [comment]
happy to make it public. but i would rather add it as a OOTB supported conversion. So add the code in here https://github.com/VerifyTests/Verify.ImageMagick/blob/main/src/Verify.ImageMagick/VerifyImageMagick.cs

thoughts?

**Comment by matt-psaltis** [comment]
I was trying to add webp as an additional image format. Adding directly to this packages source definitely works I like having the extensibility in the interim and while authors are away enjoying some well earned rest :)

**Comment by SimonCropp** [comment]
so you want to output to webp instead of png?

**Comment by matt-psaltis** [comment]
I am running tests over a WebP module for ImageSharp using ImageMagic as the comparison library.

So the result variable below represents a WebP image stream rendered by ImageSharp

Inside the test I am running the verify using:
```
await Verifier.Verify(result).UseExtension(nameof(ImageFormat.WEBP));
```

I was hoping the image conversion methods could be public so that we can do the below without having to create custom Convert methods.
```
VerifierSettings.RegisterFileConverter(nameof(ImageFormat.WEBP),
    (stream, context) => CustomVerifyImageMagick.Convert(stream, context, MagickFormat.WebP));
```
I should have included a link to this convert method as well: https://github.com/VerifyTests/Verify.ImageMagick/blob/main/src/Verify.ImageMagick/VerifyImageMagick.cs#L70

**Comment by SimonCropp** [comment]
OK :) 
this is now deployed
