### ISSUE TITLE
[Feature] Support controling the background of images generated from pdf

### ISSUE THREAD

**Issue by Greybird** [VerifyTests/Verify.ImageMagick#586]
#### Is the feature request related to a problem

I am using Verify.ImageMagick to test generated pdf contents.
However, these pdf all have white background upon rendering for users in common pdf readers, as expected for letters or written documents.
However, the png generated by Verify.ImageMagick have transparent background, which is understandable as the pdf do not specify a background. However, it makes it hard to see images content when displayed in dark-themed CI/CD systems (black text on transparent background on black/black-ish background). It also does not technically represent the end-user actual rendering.

#### Describe the solution

I would like to be able to specify a background color for image conversion to match the actual rendering of files for end users.
It could either be a global setting, or a callback to customize images that would be generated.
A global setting would be suitable for me, even if I imagine there might be situations where being able to control the behavior on a test level might make sense.

#### Describe alternatives considered

I considered replacing the pdf conversion method, which is possible, but I would have to reimplement some internal methods.

#### Additional context

-

**Comment by SimonCropp** [comment]
sounds good. happy to accept a pull request for this

**Comment by Greybird** [comment]
> sounds good. happy to accept a pull request for this

Sure, will provide a pull request in a few days, as a basis for discussion!

**Comment by SimonCropp** [comment]
i went with a slightly different approach https://github.com/VerifyTests/Verify.ImageMagick?tab=readme-ov-file#override-transparent-background

**Comment by Greybird** [comment]
Perfect for me.
I see you also fixed some mistakes I made in the csproj or gitattribute.

Thanks for taking additional time to refine my proposal, and for publishing a version very fast !

**Comment by SimonCropp** [comment]
no worries. and you did most of the work. so no thanks necessary
